---
title: An R Markdown document converted from "Designing_Objective_Function.ipynb"
output: html_document
---

```{r}
error_weights <- c(0.4,0.45,0.15)

lag_param <- length(error_weights)

df <- data.frame(error_symbolic = c('(x[1]*1.4 + x[2]*2.8 - 3)^2',
                                    '(x[1]*5.3 + x[2]*3.6 - 5)^2',
                                    '(x[1]*2.2 + x[2]*4.4 - 8)^2',
                                    '(x[1]*0.2 + x[2]*3.3 - 1)^2',
                                    '(x[1]*3.2 + x[2]*1.1 - 8)^2',
                                    '(x[1]*6.2 + x[2]*2.3 - 10)^2',
                                    '(x[1]*4.2 + x[2]*2.1 - 5)^2',
                                    '(x[1]*3.2 + x[2]*6.3 - 2)^2'))

trend <- exp(seq(1,3,length.out = length(time_seq)))

seasonality <- rep(rnorm(7,70,3),30)

rand <- rnorm(length(trend),200,1)

series <- trend + seasonality + rand

ts_df <- data.table(time = time_seq,obs = series)
```

```{r}
sample_size <- nrow(df)

df$ahead_error_symbolic <- sapply(
  1:sample_size,
  function(x) paste(df$error_symbolic[x:min(x+lag_param-1, sample_size)], collapse = " add ")
)
```

```{r}
df$ahead_num <- sapply(strsplit(df$ahead_error_symbolic,split = ' add '),length)
```

```{r}
df <- subset(df,ahead_num == length(error_weights))
```

```{r}
df$ahead_error_symbolic <- strsplit(df$ahead_error_symbolic,' add ')
```

```{r}
new_sample_size <- nrow(df)
```

```{r}
df$error_weights <- rep(list(error_weights),new_sample_size)
```

```{r}
df
```

```{r}
df$desired_column <- mapply(
  paste,
  df$error_weights,
  df$ahead_error_symbolic,
  sep = "*",
  collapse = " + "
)
```

```{r}
df
```

